### ISSUE TITLE
Does this gem include the fixes from Rails 5.1?

### ISSUE THREAD

**Issue by SamGerber-zz** [kamipo/activerecord-mysql-awesome#14]
Specifically the ones described here:
https://github.com/rails/rails/issues/27374

**Comment by kamipo** [comment]
This gem is backported some features for MySQL from 5.0 to 4.x.
The regression https://github.com/rails/rails/issues/27374 only affect to Rails 5.1.

**Comment by SamGerber-zz** [comment]
Thanks!
