### ISSUE TITLE
Migrations of datetime columns with default in String fails

### ISSUE THREAD

**Issue by a2ikm** [kamipo/activerecord-mysql-awesome#4]
Migrations like below fails:

```
add_column :users, :some_column, :datetime, default: "2015-01-02 03:04:05"
```

This seems for calling `value.to_s(:db)` where `value` is a String.
https://github.com/kamipo/activerecord-mysql-awesome/blob/master/lib/activerecord-mysql-awesome/active_record/connection_adapters/abstract_mysql_adapter.rb#L153

We can make it through by rewriting it with Time like:

```
add_column :users, :some_column, :datetime, default: Time.zone.local(2015, 1, 2, 3, 4, 5)
```

So I think this is not serious, but different from normal activerecord.

**Comment by kamipo** [comment]
Good catch!
This problem is fixed by #5.
Thank you for your reporting :smile:

**Comment by a2ikm** [comment]
Thank you :tada:

**Comment by kamipo** [comment]
v0.0.7 released.

**Comment by a2ikm** [comment]
![寿司ゆき:thanks_temaki](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/63.png)
